name: Deploy to Alibaba Cloud

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: yarn

    - name: Build project
      run: yarn build

    - name: Deploy to Alibaba Cloud
      run: |
        scp -r ./dist 8.137.114.19:/www/wwwroot/www.resgoing.com/case/3d-immersive
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
